### ISSUE TITLE
Demo links broken

### ISSUE THREAD

**Issue by gkohen** [bobbylight/AutoComplete#19]
Hi,

It seems like any of the demo links lead to a 404 page.

Thanks.

**Comment by bobbylight** [comment]
What links are you referring to?

**Comment by bobbylight** [comment]
I assumed you meant something in README.md, and fixed the broken links there (stuff stopped working when I moved to a Maven project structure, and the old fifesoft.com website got redone as well).  If there was something else you were referring to, feel free to reopen and give specifics.
