### ISSUE TITLE
Limited Autocompletion

### ISSUE THREAD

**Issue by JohM3i** [bobbylight/AutoComplete#25]
AutoCompletion is limited to only one function call. Is there a way to fix this problem ?
If you want I offer some help :)

**Comment by ChristianKrueger** [comment]
That would be very nice :)

**Comment by bobbylight** [comment]
Can you be more specific on what you want?

**Comment by chrisbln** [comment]
I think, he means an chained method call (e. g. new String().chars().max())

**Comment by Karthykeyan** [comment]
Is there any example to implement  (e. g. new String().chars().max()) ?

**Comment by bobbylight** [comment]
The AutoCompletion library isn't limited in this way.  Applications can write their own `CompletionProvider` instance that is smart enough to parse any text before the caret position and provide intelligent completions for things like chained method calls.

There are no examples of this in either the `AutoCompletion` or `RSTALanguageSupport` projects, but the only thing preventing it is time and skill (of which I'm lacking a little bit of both :)).
