### ISSUE TITLE
Substitute printStackTrace and sout's with Logger

### ISSUE THREAD

**Issue by chrisbln** [bobbylight/AutoComplete#26]
A lot of printStackTrace and System.out are called by AutoComplete (e. g. in class ASTFactory). This makes my program not very robust. 

Could you substitute this two method calls with a java.util.Logger or something like that? Let me know if you need help!

**Comment by tttwang23** [comment]
In my experience these situations the exceptions are wrapped with a RuntimeException and re-thrown.
catch (BadLocationException ex2) { throw new RuntimeException(ex2); /* should not occur */ }

**Comment by bobbylight** [comment]
`ASTFactory` is actually in `RSTALanguageSupport,` not `AutoComplete`.  I can't find any writes to sysout in `AutoComplete` that aren't guarded by a system property being set.  (As an aside, I know that's still not very robust, but at least there's no writing to stdout by the library OOTB).

I'm recreating this issue in `RSTALanguageSupport`.

**Comment by bobbylight** [comment]
Recreated as [RSTALanguageSupport issue 33](https://github.com/bobbylight/RSTALanguageSupport/issues/33).
