### ISSUE TITLE
AutoComplete wont work

### ISSUE THREAD

**Issue by DevilLordAero** [bobbylight/AutoComplete#27]
i tryed your code from example usage, but it wont working...

**Comment by bobbylight** [comment]
Please provide a link to the example you are trying to run, as well as how it is failing (stack trace, etc.).

**Comment by DevilLordAero** [comment]
https://github.com/bobbylight/AutoComplete#example-usage

**Comment by DevilLordAero** [comment]
![image](https://cloud.githubusercontent.com/assets/7568004/17621955/6d2b5364-60c1-11e6-8a63-f478c0405e42.png)
Here is..

**Comment by bobbylight** [comment]
By default, you have to hit Ctrl+Space at some point while typing for the completion popup to appear.  If you don't want to have to hit Ctrl+Space, you can enable it as follows:

```java
ac.setAutoActivationEnabled(true);
((AbstractCompletionProvider)provider).setAutoActivationRules(true, null); // Better yet, do this in createCompletionProvider() to avoid casting
```
