### ISSUE TITLE
Autocomplete description window does not show javadoc content on Windows OS

### ISSUE THREAD

**Issue by sadasblackmilk** [bobbylight/AutoComplete#29]
Hi,

We are using Autocomplete in a standalone Java application for editing Java code. When using the auto-complete functionality, the list of auto-complete choices is displayed properly.
The description window, which should contain the JavaDoc associated with the current selection, only displays the Java signature of the method with no javadoc content.
This occurs on Windows and Mac environments but works properly on Ubuntu 14.04.
We tried to set the JAVA_HOME environment variable on windows with no success...
Both JRE8 and JDK8 are installed on the windows environment.

Any help ?

Thanks.

**Comment by bobbylight** [comment]
I assume you're using `JavaLanguageSupport` from the `RSTALanguageSupport` project, is that correct?  If so, can you copy-and-paste the code you are using to set up auto-complete?

This snippet, from `org.fife.rsta.ac.demo.DemoRootPane`, should correctly show Javadoc in a popup window along with completion choices, when JAVA_HOME or your PATH points to a JDK (it looks in default locations for a src.zip file; see [LibraryInfo.getJreJarInfo](https://github.com/bobbylight/RSTALanguageSupport/blob/master/src/main/java/org/fife/rsta/ac/java/buildpath/LibraryInfo.java#L171)):

```java
LanguageSupportFactory lsf = LanguageSupportFactory.get();
LanguageSupport support = lsf.getSupportFor(SYNTAX_STYLE_JAVA);
JavaLanguageSupport jls = (JavaLanguageSupport)support;
// TODO: This API will change!  It will be easier to do per-editor
// changes to the build path.
try {
	jls.getJarManager().addCurrentJreClassFileSource();
} catch (IOException ioe) {
	ioe.printStackTrace();
}
```
