### ISSUE TITLE
Hi bob, I want to create a popup autocompleter, do you have some example? I am sorry, my english is bad.

### ISSUE THREAD

**Issue by horusdebugger** [bobbylight/AutoComplete#30]

**Comment by horusdebugger** [comment]
I solved that problem. But, now i want to show a popup autocomplete while the user is pushing the keys, do you have an example? thank you bro.

**Comment by Karthykeyan** [comment]
Hi 
I am looking for the same. On key press i need to show a popup window with possible options if there is any example it will be helpful. 

Thanks 
Karthik

**Comment by because-testing** [comment]
Yes, Team .
I'm also looking for the same feature as @horusdebugger  and @Karthykeyan  asked ,did we have any examples to follow it ?

**Comment by Karthykeyan** [comment]
Hello Guys,

This will help you 

Thanks,
Karthikeyan
---------------------------------------
import java.awt.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

import javax.swing.*;
import org.fife.ui.autocomplete.*;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rsyntaxtextarea.SyntaxConstants;
import org.fife.ui.rtextarea.RTextScrollPane;

public class AutoCompleteDemo extends JFrame {

   public AutoCompleteDemo() {

      JPanel contentPane = new JPanel(new BorderLayout());
      RSyntaxTextArea textArea = new RSyntaxTextArea(20, 60);
      textArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_JAVA);
      textArea.setCodeFoldingEnabled(true);
      contentPane.add(new RTextScrollPane(textArea));

      // A CompletionProvider is what knows of all possible completions, and
      // analyzes the contents of the text area at the caret position to
      // determine what completion choices should be presented. Most instances
      // of CompletionProvider (such as DefaultCompletionProvider) are designed
      // so that they can be shared among multiple text components.
      CompletionProvider provider = createCompletionProvider();

      // An AutoCompletion acts as a "middle-man" between a text component
      // and a CompletionProvider. It manages any options associated with
      // the auto-completion (the popup trigger key, whether to display a
      // documentation window along with completion choices, etc.). Unlike
      // CompletionProviders, instances of AutoCompletion cannot be shared
      // among multiple text components.
      final AutoCompletion ac = new AutoCompletion(provider);
      ac.install(textArea);

      textArea.addKeyListener(new KeyAdapter() {
         @Override
         public void keyReleased(KeyEvent e) {
            ac.doCompletion();
         }
      });
      setContentPane(contentPane);
      setTitle("AutoComplete Demo");
      setDefaultCloseOperation(EXIT_ON_CLOSE);
      pack();
      setLocationRelativeTo(null);

   }

   /**
    * Create a simple provider that adds some Java-related completions.
    */
   private CompletionProvider createCompletionProvider() {

      // A DefaultCompletionProvider is the simplest concrete implementation
      // of CompletionProvider. This provider has no understanding of
      // language semantics. It simply checks the text entered up to the
      // caret position for a match against known completions. This is all
      // that is needed in the majority of cases.
      DefaultCompletionProvider provider = new DefaultCompletionProvider();

      // Add completions for all Java keywords. A BasicCompletion is just
      // a straightforward word completion.
      provider.addCompletion(new BasicCompletion(provider, "abstract"));
      provider.addCompletion(new BasicCompletion(provider, "assert"));
      provider.addCompletion(new BasicCompletion(provider, "break"));
      provider.addCompletion(new BasicCompletion(provider, "case"));
      // ... etc ...
      provider.addCompletion(new BasicCompletion(provider, "transient"));
      provider.addCompletion(new BasicCompletion(provider, "try"));
      provider.addCompletion(new BasicCompletion(provider, "void"));
      provider.addCompletion(new BasicCompletion(provider, "volatile"));
      provider.addCompletion(new BasicCompletion(provider, "while"));

      // Add a couple of "shorthand" completions. These completions don't
      // require the input text to be the same thing as the replacement text.
      provider.addCompletion(new ShorthandCompletion(provider, "sysout",
            "System.out.println(", "System.out.println("));
      provider.addCompletion(new ShorthandCompletion(provider, "syserr",
            "System.err.println(", "System.err.println("));

      return provider;

   }

   public static void main(String[] args) {
      // Instantiate GUI on the EDT.
      SwingUtilities.invokeLater(new Runnable() {
         public void run() {
            try {
               String laf = UIManager.getSystemLookAndFeelClassName();
               UIManager.setLookAndFeel(laf);
            } catch (Exception e) { /* Never happens */ }
            new AutoCompleteDemo().setVisible(true);
         }
      });
   }

}

**Comment by because-testing** [comment]
thanks @Karthykeyan  , I had found another good option to show the auto complete manually ,the idea is as following:
* Map the auto complete shortcut(ctrl+space) to new key shortcut or not mappped ,depends on your need.
* Get the keymap action listener  in RSynaxTextarea ,see below full code:

`// map the F4 key action to auto complete
		changeAutoCompleteKeyF4(textArea, null); // use default F4 shortcut
		// add the popup menu after the cut section
		JPopupMenu popupMenu = textArea.getPopupMenu();
		popupMenu.insert(new JPopupMenu.Separator(), 6);
		JMenuItem autocomplete = new JMenuItem("Auto Complete");
		autocomplete.setMnemonic('A');
		autocomplete.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_F4, 0));
		autocomplete.addActionListener(textArea.getActionForKeyStroke(KeyStroke.getKeyStroke(KeyEvent.VK_F4, 0)));
		popupMenu.insert(autocomplete, 7);
		popupMenu.insert(new JPopupMenu.Separator(), 8);`

**Comment by bobbylight** [comment]
If you want to show it on a specific key press/combination, you can use `AutoCompletion.setTriggerKey(KeyStroke)` to set what keystroke triggers the completion popup (the default being Ctrl+Space/Cmd+Space on Mac).  If you want it to display while typing random characters (such as [A-Za-z]),  you should use a combination of the following:

* `AutoCompletion.setAutoActivationEnabled(boolean)` - Set to `true` to have the auto-complete popup window automatically display when certain characters are pressed (see below)
* `CompletionProviderBase.setAutoActivationRules(boolean, String)` - Set what characters should trigger the auto-activation of the autocomplete popup.  For example, `setAutoActivationRules(true, ".")` will cause the popup to display after the user types a letter or a "." (after a small delay).

Thus, a little configuration of both the `AutoCompletion` and the `CompletionProvider` should do the trick.
