### ISSUE TITLE
Util.startsWithIgnoreCase() is non-standard NLS wise

### ISSUE THREAD

**Issue by tttwang23** [bobbylight/AutoComplete#32]
probably a latent issue

String.java grepcode viewing showed that the implementation there uses
                char c1 = str.charAt(indx);
                char c2 = prefix.charAt(indx);
                if (c1 != c2)
                {
                    c1 = Character.toUpperCase(c1);
                    c2 = Character.toUpperCase(c2);
                    if (c1 != c2)
                    {
                        c1 = Character.toLowerCase(c1);
                        c2 = Character.toLowerCase(c2);
                        if (c1 != c2)
                        {
                            return false;
                        }
                    }
                }

where Util.startsWithIgnoreCase() is
  if (Character.toLowerCase(c1) != Character.toLowerCase(c2)) return false;

They are quite different.

**Comment by tttwang23** [comment]
Turned out quite a number of methods in the String class does not consider characters outside the BMP range.  I just wrote a bunch of methods to support those supplementary characters.

This is my current cut of startsWithIgnoreCase:

```
    public static boolean startsWithIgnoreCase(
        final CharSequence str, final CharSequence prefix)
    {
        final int prefixLen = prefix.length();
        final int strLen = str.length();
        int prefixPtr = 0;
        int strPtr = 0;
        for (;;)
        {
            if ((strPtr < strLen) && (prefixPtr >= prefixLen))
            {
                return true; // prefix ran out
            }
            if ((strPtr >= strLen) && (prefixPtr < prefixLen))
            {
                return false; // str ran out
            }
            if ((strPtr >= strLen) && (prefixPtr >= prefixLen))
            {
                break; // They are equal (case insensitive).
            }
            int s1 = Character.codePointAt(prefix, prefixPtr);
            prefixPtr += Character.charCount(s1);
            int t1 = Character.codePointAt(str, strPtr);
            strPtr += Character.charCount(t1);
            if (s1 != t1)
            {
                s1 = Character.toUpperCase(s1);
                t1 = Character.toUpperCase(t1);
                if (s1 != t1)
                {
                    s1 = Character.toLowerCase(s1);
                    t1 = Character.toLowerCase(t1);
                    if (s1 != t1)
                    {
                        return false;
                    }
                }
            }
        }
        return true;
    }
```

**Comment by tttwang23** [comment]
A comment about why toLowerCase(x) is different than toLowerCase(toUpperCase(x)):  The Latin lower case "i" without a dot (0x131) is case-insensitive to the regular lower case "i".  However, since 0x131 is already lower case, toLowerCase(0x131) is just itself.  toLowerCase(toUpperCase(0x131)) returns the regular lower case "i".  Thus it is the standard mechanism for case-insensitive detection.

**Comment by bobbylight** [comment]
Thanks for this.  I'll fix this for BMP characters such as 0x131 from your example, but I won't go further than that.  The Util class is meant  primarily for use in the library to check whether a token typed in code matches a certain set of identifiers (keywords, method names, etc.), and I doubt many programming languages reach outside of the BMP.

**Comment by tttwang23** [comment]
The most popular characters outside the BMP are the Emoji symbols.  For JRE8 the only lowercase / uppercase distinctions outside the BMP are the Deseret alphabets, which are no longer in active use.
