### ISSUE TITLE
Suggested copyright boiler-plate

### ISSUE THREAD

**Issue by tttwang23** [bobbylight/AutoComplete#33]
```
/*
 * Copyright (c) 2012-20XX, Robert Futrell and the AutoComplete project contributors
 *
 * This library is distributed under a modified BSD license.  See the included
 * AutoComplete.License.txt file for details.
 *
 */
```

where XX is the most recent year that said file was modified

I will use this boiler-plate for files that I submit in a pull request.

**Comment by bobbylight** [comment]
Very well.  The copyright line is not strictly necessary IMO, just the reference to the license file.  Note I'm personally moving towards:

```java
/*
 * 05/11/2012
 *
 * This library is distributed under a modified BSD license.  See the included
 * AutoComplete.License.txt file for details.
 */
```

The creation date is pretty useless, but old habits die hard.
