### ISSUE TITLE
"Hook" into parser (Question)

### ISSUE THREAD

**Issue by Haeri** [bobbylight/AutoComplete#39]
I have a question regarding the language parser. I support a quick build and run feature in my text editor. But to compile java code, the java file has to have the same name as the class. Therefore, I attempted to parse the class name by myself, and failed miserably. Now I was wondering, is there a way to "tap" into the autocomplete parser and get some information like the class name?

Also further down the line, I would love to implement a sort of integrated color picker, that detects a color hex in the code and offers a color dialog to quickly adjust said color. So in a broader sense, is there some sort of "hooks" provided that allow to benefit from the already parsed text, so we don't have to do our own parsing?

**Comment by tttwang23** [comment]
This is not a question about AutoComplete, but RSyntaxTextArea.  Possibly you can create a sub-class of org.fife.ui.rsyntaxtextarea.modes.JavaTokenMaker, and capture the package and class name of the source as it is being read in.

However, in a real project typically you don't want to compile in your source directory because it would mess up the source control convention.  So the quick build and run feature is at best a check-mark feature.

**Comment by bobbylight** [comment]
I tried my hand at writing a parser for Java code a while back, see the RSTALanguageSupport project.  It's meant to add code completion to RSTA for Java (among other languages), but for something like this you could just use its [JavaParser](https://github.com/bobbylight/RSTALanguageSupport/blob/master/src/main/java/org/fife/rsta/ac/java/JavaParser.java) class directly.

Hopefully the Javadoc comment for that class is enough to get you started.  Just add it to an RSTA instance and listen for `JavaParser.PROPERTY_COMPILATION_UNIT` property change events to be fired.  When you receive such an event, the first [TypeDeclaration](https://github.com/bobbylight/RSTALanguageSupport/blob/master/src/main/java/org/fife/rsta/ac/java/rjc/ast/TypeDeclaration.java) in the returned [CompilationUnit](https://github.com/bobbylight/RSTALanguageSupport/blob/master/src/main/java/org/fife/rsta/ac/java/rjc/ast/CompilationUnit.java) should be the first class in the file, from which you can grab the class/interface/enum's name.

As an aside:  while the Java code compiletion in RSTALanguageSupport isn't complete (and may not recognize all Java 8 constructs), it should always work for the specific use case outlined here.

About the color picker, you could do the following:

1. Override the [createPopupMenu()](https://github.com/bobbylight/RSyntaxTextArea/blob/master/src/main/java/org/fife/ui/rtextarea/RTextArea.java#L448) method
2. After calling super.createPopupMenu(), add a menu item, something like "Change color for token at caret".
3. For your new menu item's action, get the token type at the caret position (`Token token = textArea.modelToToken(textArea.getCaretPosition());`)
4. Get that token type's color by querying the syntax scheme:  `textArea.getSyntaxScheme()`
5. From here on out, it's on you - display a modal dialog to let them select a color and optional font, then update the syntax scheme.

**Comment by Haeri** [comment]
Ok thanks for the hint about the class name. I would never have found that on my own :D

But I think there was a miscommunication about the second question about the color. To reiterate, I am trying to do something like this:

![Color Picker](https://i.github-camo.com/467c72e686f00893c3d36bf46499e76c10f31787/68747470733a2f2f6769746875622e636f6d2f74686f6d61736c696e647374726f6d2f636f6c6f722d7069636b65722f7261772f6d61737465722f707265766965772e676966)
