### ISSUE TITLE
Examples on how to use autocomplete

### ISSUE THREAD

**Issue by ruuddb** [bobbylight/AutoComplete#42]
Do you have examples on how to use autocomplete?
How do I use the different autocomplete types?

I'm looking for a way to autocomplete things like a.b.c where typing "a." results in showing
every defined item that starts with a.

**Comment by bobbylight** [comment]
Honestly, the best place to look for examples of using this library are in the sister project, [RSTALanguageSupport](https://github.com/bobbylight/RSTALanguageSupport).  That project uses it to implement code completion, to varying degrees of complexity, for several languages.  CSS, Perl, and C are goos starting points.  C and CSS read their completions from XML files, whereas Perl not only does that, but also calls out to the system perl process for squiggle-underlining of errors.
