### ISSUE TITLE
Is there any easy way to get the jar file?

### ISSUE THREAD

**Issue by MrSoUndso** [bobbylight/AutoComplete#47]
Hi bobbylight,

I just wanted to ask you, if there is any maven or direct download for the jar, so I don't need to compile all your code myself.

I hope you can help me and I don't look too dumb :) 

Thanks in advance
Mr_SoUndso

**Comment by bobbylight** [comment]
Sure, you can grab autocomplete, or any RSTA-related artifact, via Maven or gradle:

http://search.maven.org/#artifactdetails%7Ccom.fifesoft%7Cautocomplete%7C2.6.1%7Cjar

I also try to put precompiled jars on SourceForge here:

https://sourceforge.net/projects/rsyntaxtextarea/files/

Though sometimes I forget to, and SourceForge isn't exactly the best place to host open source these days.  :)

Moving forward, I'll start adding the compiled jars to the [Releases page](https://github.com/bobbylight/AutoComplete/releases) as well.
