### ISSUE TITLE
[SOLVED] Demo does not work

### ISSUE THREAD

**Issue by Skyost** [bobbylight/AutoComplete#50]
Hi,
I tried your demo (in the README.md) with RSyntaxTextArea v2.6.1 and AutoComplete v2.6.1 and it does not work.
The popup list just does not show up, and sadly I have no more info.

Thanks,
- Skyost

**Comment by Zezombye** [comment]
You should add these lines:
```
ac.setAutoActivationEnabled(true); //removes the need to input ctrl+space for autocomplete
ac.setAutoCompleteSingleChoices(false); //single choices are not automatically inputted
ac.setAutoActivationDelay(0); //no delay
```
Only the first line is necessary but the other 2 allow for a good autocomplete (these should be enabled by default).

**Comment by Skyost** [comment]
Okay, thanks for your reply. I didn't know that we have to use CTRL + SPACE for autocomplete. But sadly, even with your answer, we still have to use CTRL + SPACE to get a working autocompletion 😞

**Comment by Zezombye** [comment]
Oh right, I think you also have to do this: `provider.setAutoActivationRules(true, null);`

**Comment by Skyost** [comment]
Exactly what I've searched for. Thanks !
