### ISSUE TITLE
Register triggerKey for each Completion provider  when using RoundRobinAutoCompletion

### ISSUE THREAD

**Issue by heyphord** [bobbylight/AutoComplete#52]
Hello Bob,
I have added 3 completion providers to a RoundRobinAutoCompletion Instance.
I want to display a pop up window for a particular completionProvider on a particular keystrok, i dont want to cycle through the completion providers before i get the require completion provider.

For example
shift @, should show only the 1st Completion Provider
shift $, should show only the 2nd Completion Provider
shift #, should show only the 3rd Completion Provider

Please is this possible.
Thanks in advance

**Comment by subinsunny** [comment]
Hi,
Did you find a way to make it work?
Even I have a similar requirement, wherein on press of '<' I want to show xml tags and on press of space, show attributes.

Thanks

**Comment by heyphord** [comment]
Yeah @subinsunny , i found a way without using RoundRobinAutoCompletion. Create a class that inherits DefaultCompletionProvider and overide isValidChar ()  . 
Then use that class when instantiating the AutoCompletion class

I'll upload the code s shortly

**Comment by subinsunny** [comment]
Hey @heyphord , Thanks for the reply, I tried but couldn't make it work... Waiting for your code. :)

**Comment by bobbylight** [comment]
Also note that, for XML, you can use [RSTALanguageSupport](https://github.com/bobbylight/RSTALanguageSupport) for prebuilt XML code completion utilities.  From the doc there:

* XML
  * Ctrl+Shift+O (Cmd+Shift+O on OS X) opens a "Go to Member" popup, a la Eclipse.
  * `XmlOutlineTree` component provides a tree view of an XML file that is updated live with edits.
