### ISSUE TITLE
Given Example doesnt even work :/

### ISSUE THREAD

**Issue by ghost** [bobbylight/AutoComplete#54]
Well... I'm currently programming my own editor for a school-project.
When trying to add the Autocomplete everything works, but the autocompletition doesnt pop up....

**Comment by bobbylight** [comment]
@Vatolino, can you point to the specific example that does not work for you?

**Comment by copypasteearth** [comment]
no autocomplete pop up

`public class CodeEditor extends JFrame {

    public CodeEditor() {

        JPanel contentPane = new JPanel(new BorderLayout());
        RSyntaxTextArea textArea = new RSyntaxTextArea(20, 60);
        textArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_JAVA);
        textArea.setCodeFoldingEnabled(true);
        contentPane.add(new RTextScrollPane(textArea));

        // A CompletionProvider is what knows of all possible completions, and
        // analyzes the contents of the text area at the caret position to
        // determine what completion choices should be presented. Most instances
        // of CompletionProvider (such as DefaultCompletionProvider) are designed
        // so that they can be shared among multiple text components.
        CompletionProvider provider = createCompletionProvider();

        // An AutoCompletion acts as a "middle-man" between a text component
        // and a CompletionProvider. It manages any options associated with
        // the auto-completion (the popup trigger key, whether to display a
        // documentation window along with completion choices, etc.). Unlike
        // CompletionProviders, instances of AutoCompletion cannot be shared
        // among multiple text components.
        AutoCompletion ac = new AutoCompletion(provider);
        ac.setListCellRenderer(new CompletionCellRenderer());
        ac.setShowDescWindow(true);

        ac.setParameterAssistanceEnabled(true);

        ac.install(textArea);
        

        ToolTipManager.sharedInstance().registerComponent(textArea);

        setContentPane(contentPane);
        setTitle("AutoComplete Demo");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        pack();
        setLocationRelativeTo(null);

    }

    /**
     * Create a simple provider that adds some Java-related completions.
     */
    private CompletionProvider createCompletionProvider() {

        // A DefaultCompletionProvider is the simplest concrete implementation
        // of CompletionProvider. This provider has no understanding of
        // language semantics. It simply checks the text entered up to the
        // caret position for a match against known completions. This is all
        // that is needed in the majority of cases.
        DefaultCompletionProvider provider = new DefaultCompletionProvider();

        // Add completions for all Java keywords. A BasicCompletion is just
        // a straightforward word completion.
        provider.addCompletion(new BasicCompletion(provider, "abstract"));
        provider.addCompletion(new BasicCompletion(provider, "assert"));
        provider.addCompletion(new BasicCompletion(provider, "break"));
        provider.addCompletion(new BasicCompletion(provider, "case"));
        // ... etc ...
        provider.addCompletion(new BasicCompletion(provider, "transient"));
        provider.addCompletion(new BasicCompletion(provider, "try"));
        provider.addCompletion(new BasicCompletion(provider, "void"));
        provider.addCompletion(new BasicCompletion(provider, "volatile"));
        provider.addCompletion(new BasicCompletion(provider, "while"));
        provider.addCompletion(new BasicCompletion(provider, "public"));
        provider.addCompletion(new BasicCompletion(provider, "private"));
        provider.addCompletion(new BasicCompletion(provider, "protected"));
        provider.addCompletion(new BasicCompletion(provider, "static"));
        provider.addCompletion(new BasicCompletion(provider, "final"));


        // Add a couple of "shorthand" completions. These completions don't
        // require the input text to be the same thing as the replacement text.
        provider.addCompletion(new ShorthandCompletion(provider, "sysout",
                "System.out.println(", "System.out.println("));
        provider.addCompletion(new ShorthandCompletion(provider, "syserr",
                "System.err.println(", "System.err.println("));

        return provider;

    }

    public static void main(String[] args) {
        // Instantiate GUI on the EDT.
        SwingUtilities.invokeLater(() -> {
            try {
                String laf = UIManager.getSystemLookAndFeelClassName();
                UIManager.setLookAndFeel(laf);
            } catch (Exception e) { /* Never happens */ }
            new CodeEditor().setVisible(true);
        });
    }

}`

**Comment by bobbylight** [comment]
Note that by default, you need to type Ctrl+Space for the completion popup to appear.  Are you doing that?

**Comment by copypasteearth** [comment]
No I didn't do that, I'll try later, is there a way to make it automatically pop up? That's what I really want

**Comment by bobbylight** [comment]
To have it automatically pop up is a two step process:

First, enable it via `AutoCompletion.setAutoCompleteEnabled(true)`.  Call this on the AutoCompletion instance you create, before setting everything else up.

Then, what keys trigger the completion popup to automatically display is a property of the `CompletionProvider`.  e.g. should it only appear when the user types ".", or should it appear whenever any letter is typed, or something else?  This is configurable since determining a set of possible code completions can be an expensive operation, so it should be set conservatively if possible.  Any `CompletionProvider` extending `CompletionProviderBase` (e.g. any `DefaultCompletionProvider`) can have this configured via the `setAutoActivationRules(boolean letters, String others)` method.

**Comment by bobbylight** [comment]
Closing as a solution was provided.
