### ISSUE TITLE
AutoComplete for Groovy using groovysh

### ISSUE THREAD

**Issue by rednoah** [bobbylight/AutoComplete#55]
Has anybody had success integrating `AutoComplete` with [groovysh](https://github.com/groovy/groovy-core/tree/master/subprojects/groovy-groovysh/src/main/groovy/org/codehaus/groovy/tools/shell) for Groovy AutoComplete Support?

**Comment by bobbylight** [comment]
Looks like no :(  Note if you went ahead and did this yourself, I'd consider adding it to the sister `RSTALanguageSupport` project if it's useful to folks in general.
