### ISSUE TITLE
TipUtil uses incorrect color for description editor pane

### ISSUE THREAD

**Issue by patrickangle** [bobbylight/AutoComplete#57]
The background color of the description editor pane is being set based on the Color in `ToolTip.background`, but the corresponding foreground color is being set based on `Label.foreground` instead of `ToolTip.foreground`. The result is that in some darker look and feels (where labels are white but tooltips still have yellow backgrounds) the description text is difficult to see on top of the background.

Changing the label foreground color isn't a great solution, because the rest of the look and feel relies on the labels being a light color on top of the dark backgrounds.

<img width="1291" alt="Screen Shot 2019-08-03 at 5 07 49 PM" src="https://user-images.githubusercontent.com/29403422/62416907-66fbfb80-b611-11e9-9ef5-41e6d1adc82e.png">

**Comment by bobbylight** [comment]
Thanks for the bug report!

**Comment by bobbylight** [comment]
While this should be fixed in the next release, note a workaround in the meantime could be to change the background color of that description window (I know sometimes using the tool tip color can look a little odd) via `AutoCompletion.setDescriptionWindowColor(Color)`.
