### ISSUE TITLE
TemplateCompletion doesn't work at all

### ISSUE THREAD

**Issue by Alex-www** [bobbylight/AutoComplete#61]
ShorthandCompletion et al work, but TemplateCompletion doesn't.

I've tracked it as far as getReplacementText **is** called for a TemplateCompletion (and returns null as expected and coded), but getInsertionInfo is **NOT** called.

So the triggering token is removed from the textarea, but nothing else happens, no text inserted.

I even tried with none but just the for-loop example, CTRL+SPACE brings up the selection window, trigger for-loop, nuffin but an empty space where the replacement text should be inserted.

(Using rsyntaxtextarea 3.0.4 and autocomplete 3.0.2)

TIA

**Comment by bobbylight** [comment]
These seem to work in the `RSTALanguageSupport` project, at least `JavaScriptTemplateCompletion`s do.  Can you provide an [SSCCE](http://sscce.org/) that demonstrates the problem?

As an aside, it's interesting to note that `FunctionCompletion` doesn't extend `TemplateCompletion`, but rather implements `ParameterizedCompletion` itself.

**Comment by Alex-www** [comment]
```
import java.awt.*;
import javax.swing.*;
import org.fife.ui.autocomplete.*;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rsyntaxtextarea.SyntaxConstants;
import org.fife.ui.rtextarea.RTextScrollPane;

public class RSABug61 extends JFrame {

   public RSABug61() {

      JPanel contentPane = new JPanel(new BorderLayout());
      RSyntaxTextArea textArea = new RSyntaxTextArea(20, 60);
      textArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_JAVA);
      textArea.setCodeFoldingEnabled(true);
      contentPane.add(new RTextScrollPane(textArea));

      CompletionProvider provider = createCompletionProvider();

      AutoCompletion ac = new AutoCompletion(provider);
      ac.install(textArea);

      setContentPane(contentPane);
      setTitle("AutoComplete Demo");
      setDefaultCloseOperation(EXIT_ON_CLOSE);
      pack();
      setLocationRelativeTo(null);

   }

   /**
    * Create a simple provider that adds some Java-related completions.
    */
   private CompletionProvider createCompletionProvider() {

      DefaultCompletionProvider provider = new DefaultCompletionProvider();

      String template = "for (int ${i} = 0; ${i} < ${array}.length; ${i}++) {\n\t${cursor}\n}";
      Completion tc = new TemplateCompletion(provider, "for", "for-loop", template);
      provider.addCompletion(tc);

      return provider;

   }

   public static void main(String[] args) {
      // Instantiate GUI on the EDT.
      SwingUtilities.invokeLater(() -> {
        try {
           String laf = UIManager.getSystemLookAndFeelClassName();
           UIManager.setLookAndFeel(laf);
        } catch (Exception e) { /* Never happens */ }
        new RSABug61().setVisible(true);
      });
   }

}
```

**Comment by bobbylight** [comment]
Looks like you didn't call `ac.setParameterAssistanceEnabled(true)`, which is required for any `ParameterizedCompletion` to work.  I don't think this is really documented anywhere so I added Javadoc describing this requirement to the `ParameterizedCompletion` interface as well as its implementations, `TemplateCompletion` and `FunctionCompletion`.
