### ISSUE TITLE
ParameterizedCompletionDescriptionToolTip is not sized correctly

### ISSUE THREAD

**Issue by SlimShady0208** [bobbylight/AutoComplete#8]
We are currently using RSyntaxTextArea (2.5.3) and AutoComplete (2.5.1) in our application in a script editing context. But there seems to be an calculation issue in tool tip bounds when using a parameterized completion.

It looks like it is not appropriate for multi-lined text. 

![autocompleteissue](https://cloud.githubusercontent.com/assets/949775/4186039/40263ad0-375d-11e4-8c6e-f9f5aa4ef817.png)

Is this a known issue? Could you fix the height of the tooltip? Or are we doing something wrong?

Best regards,
SlimShady

**Comment by bobbylight** [comment]
Closing as this is an old ticket, and I don't have an example to reproduce it with. Please reopen if you come up with an [SSCCE](https://sscce.org/) that demonstrates the problem!
