### ISSUE TITLE
Customize suggestion format

### ISSUE THREAD

**Issue by ddugovic** [bobbylight/AutoComplete#85]
We would like to use this tool to display suggestions in the format `FirstName LastName <User@Domain>`.

**Comment by bobbylight** [comment]
Assuming you are using [BasicCompletions](https://github.com/bobbylight/AutoComplete/blob/master/AutoComplete/src/main/java/org/fife/ui/autocomplete/BasicCompletion.java), you can override the cell renderer used to render as you see fit. The `value` passed in will be the `Completion` to render:

```java
autoCompletion.setListCellRenderer(new CompletionCellRenderer() {
  @Override
  protected void prepareForOtherCompletion(JList list,
      Completion c, int index, boolean selected, boolean hasFocus) {
    // ... Your implementation
  }
});
```

Extending [CompletionCellRenderer](https://github.com/bobbylight/AutoComplete/blob/master/AutoComplete/src/main/java/org/fife/ui/autocomplete/CompletionCellRenderer.java) like the example above will allow you to mix your own `Completion`s (usually `BasicCompletion`, but you could also use your own subclass), but you can use any `ListCellRenderer` implementation you want if you don't need that functionality and would rather keep things simpler.
